databases:
  - name: postgres
    databaseName: postgres
    user: postgres.ysdyzkckjipnokbapvke

services:
  - type: web
    name: logFormatterWebapp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false

