development:
  adapter: redis
  port: 6379
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  port: 6379
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
