default: &default
  adapter: postgresql
  database: <%= ActiveRecord::Base.connection_db_config.configuration_hash[:database] %>
  username: <%= ActiveRecord::Base.connection_db_config.configuration_hash[:username] %>
  password: <%= ActiveRecord::Base.connection_db_config.configuration_hash[:password] %>
  host: <%= ActiveRecord::Base.connection_db_config.configuration_hash[:host] %>
  port: <%= ActiveRecord::Base.connection_db_config.configuration_hash[:port] %>


development:
  <<: *default

# test:
#   adapter: test

production:
  <<: *default