development:
  adapter: redis
  url: <%= "redis://#{Rails.application.config.x.redis[:host]}:#{Rails.application.config.x.redis[:port]}/#{Rails.application.config.x.redis[:db]}" %>
  ssl: <%= Rails.application.config.x.redis[:ssl] %>
  password: <%= Rails.application.config.x.redis[:password] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= "redis://#{Rails.application.config.x.redis[:host]}:#{Rails.application.config.x.redis[:port]}/#{Rails.application.config.x.redis[:db]}" %>
  ssl: <%= Rails.application.config.x.redis[:ssl] %>
  password: <%= Rails.application.config.x.redis[:password] %>