development:
  adapter: redis
  url: <%= "#{Rails.application.config.x.redis[:ssl]?'rediss':'redis'}://#{Rails.application.config.x.redis[:host]}:#{Rails.application.config.x.redis[:port]}/#{Rails.application.config.x.redis[:db]}" %>
  password: <%= Rails.application.config.x.redis[:password] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= "#{Rails.application.config.x.redis[:ssl]?'rediss':'redis'}://#{Rails.application.config.x.redis[:host]}:#{Rails.application.config.x.redis[:port]}/#{Rails.application.config.x.redis[:db]}" %>
  password: <%= Rails.application.config.x.redis[:password] %>