default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: logformatter_development
  username: postgres
  password: password

# test:
#   <<: *default
#   database: logformatter_test

production:
  <<: *default
  host: <%= ENV["APP_DATABASE_HOST"] %>
  database: postgres
  username: postgres
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  sslmode: verify-full
  sslrootcert: <%= ENV['SSL_CERTIFICATE_PATH'] %>