default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["APP_DATABASE_HOST"] %>
  database: logformatter_development
  username: postgres
  password: password
  sslmode: verify-full
  sslrootcert: prod-ca-2021.crt

test:
  <<: *default
  database: logformatter_test         # テスト環境用のデータベース名。

production:
  <<: *default
  host: <%= ENV["APP_DATABASE_HOST"] %>
  database: postgres
  username: postgres
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  sslmode: verify-full
  sslrootcert: prod-ca-2021.crt